# Generated by Django 5.1.7 on 2025-03-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime_cr', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='Tags', to='todo_list.tag')),
            ],
        ),
    ]
